name: GraalVM Native Builds
on: [push, pull_request]
jobs:
  build:
    name: cli-utils on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeCompile
      
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: cli-utils-${{ matrix.os }}
          path: ${{ github.workspace }}/**/build/native/nativeCompile/*
          if-no-files-found: error
