name: Main Workflow
on: [push, pull_request]
jobs:
  build:
    name: cli-utils on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: nativeCompile

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: cli-utils-${{ matrix.os }}
          path: ${{ github.workspace }}/**/build/native/nativeCompile/*
          if-no-files-found: error

  tag:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DRY_RUN: true
          INITIAL_VERSION: 1.0.0

  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
